<?php ///[i18n:Long Text Translation]
///such as: 'Sorry, we are unable to reset password ...' => 'Sorry, we are unable to reset password for the provided email address.',

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

	/**
	 * Modules
	 */
	///\vendor\yongtiger\yii2-user\src\Module.php
	'This site has been closed registration.' => '本站已经关闭注册。',
	'This site has been closed login.' => '本站已经关闭登陆。',
	'My Account' => '我的账户',
	'Account Security' => '账户安全',
	'User Preference' => '偏好设置',
	'User Status' => '账户状态',
	'User Count' => '统计数据',
	'User Profile' => '个人资料',
	//////[Yii2 uesr: verifycode]
	'Verification Code' => '验证码',
	'Click to change another verification code.' => '点击切换验证码',


	/**
	 * Controllers
	 */
	///\vendor\yongtiger\yii2-user\src\controllers\SecurityController.php
	'Login failed! A user bound to this oAuth client was not found.' => '登陆失败！没找到与第三方认证绑定的用户。',
	//////[Yii2 uesr:account oauth]
	'Already connected. No need to connect again.' => '已经绑定该第三方认证，无需再次绑定。',
	'Successfully connect.' => '绑定成功。',
	'Failed connect!' => '绑定失败！',
	'Successfully disconnect.' => '解绑成功。',
	'Failed disconnect!' => '解绑失败！',

	///\vendor\yongtiger\yii2-user\src\controllers\AccountController.php
	//////[Yii2 uesr:account]
	'Invalid action!' => '无效操作！',
	
	///\vendor\yongtiger\yii2-user\src\controllers\UserController.php
	'Successfully created.' => '创建成功。',
	'Successfully updated.' => '更新成功。',
	'Successfully deleted.' => '删除成功。',
	'Failed to delete!' => '删除失败！',
	'Deleted {0} users.' => '共删除了 {0} 个用户。',


	/**
	 * Models
	 */
	///\vendor\yongtiger\yii2-user\src\models\User.php
	'"findIdentityByAccessToken" is not implemented.' => '"findIdentityByAccessToken"没有实现。',
	'Status' => '用户状态',
	'Created At' => '创建时间',
	'Updated At' => '更新时间',

	///\vendor\yongtiger\yii2-user\src\models\UserSearch.php
	'Created Date Range' => '创建日期范围',
	'Updated Date Range' => '更新日期范围',

	///\vendor\yongtiger\yii2-user\src\models\SignupForm.php
	'Username' => '用户名',
	'Email' => '邮箱',
	'Password' => '密码',
	'This username has already been taken.' => '用户名已经被占用。',
	'This email address has already been taken.' => '邮箱已经被占用。',
	'The username only contains letters ...' => '用户名由字母、汉字、数字及下划线组成，且不能以数字和下划线开头。',	///[Yii2 uesr:username]
	'The password only contains letters ...' => '密码只能含6-20位数字、大小写字母和“-”、“_”等特殊字符。',	///[Yii2 uesr:password]
	//////[Yii2 uesr:repassword]
	'Repeat Password' => '再次输入密码',
	'The two passwords do not match.' => '两次输入的密码不一致。',
	//////[Yii2 uesr:activation via email:signup]
	'An activation email will be sent.' => '系统将发送激活邮件到您的邮箱。',
	'Successfully registered.'  => '注册成功。',

	///\vendor\yongtiger\yii2-user\src\models\LoginForm.php
	'Username or Email' => '用户名或邮箱',
	'Username' => '用户名',
	'Password' => '密码',
	'Remember me' => '记住我',
	'Incorrect username or password.' => '用户名或密码不正确。',
	'Your account is invalid!' => '您的账户无效！',
	'Your account is not activated!' => '您的账户没有激活！',
	'Click [{resend}] an activation Email.' => '点击 [{resend}] 激活邮件。',
	'Resend' => '重新发送',
	'Signup with email activation is not enabled!' => '系统激活邮件功能没有开启！',
	'Please contact to the administrator.' => '请联系管理员。',

	///\vendor\yongtiger\yii2-user\src\models\ChangeForm.php
	//////[Yii2 uesr:account]
	'Incorrect password.' => '密码不正确。',
	'Successfully changed.' => '修改成功。',

	///\vendor\yongtiger\yii2-user\src\models\ChangePasswordForm.php
	//////[Yii2 uesr:account]
	'New Password' => '新密码',

	///\vendor\yongtiger\yii2-user\src\models\SendTokenForm.php
	'There is no user with such email.' => '没有用户使用该邮箱。',
	'Please do not send email repeatedly! Try again in {valid-duration}.' => '请不要重复发送验证邮件！过 {valid-duration} 再尝试发送。',
	'Failed to find a user!' => '没有找到用户！',
	'Activation mail of the registration from ' => '注册激活邮件 - ',
	'Please check your email [{youremail}] to activate your account.'  => '请查收您的邮箱 [{youremail}] 以激活账户。',
	'Password reset for ' => '密码重置 ',
	'Please check your email [{youremail}] for further instructions.' => '请查收您的邮箱 [{youremail}] 进行下一步操作。',
	'Verification mail from ' => '邮箱验证邮件 - ',
	'Please check your email [{youremail}] to verify your email.' => '请查收您的邮箱 [{youremail}] 以验证您的邮箱。',

	///\vendor\yongtiger\yii2-user\src\models\TokenHandler.php
	'The token has been expired!' => 'Token已经过期！',
	'Your account has been successfully activated ...' => '您的账户已经被成功激活。您可以用注册时填写的用户名和密码进行登陆。',
	'Your account has not been activated! Please try again.' => '您的账户没有被激活！请重新试一试。',
	'Please reset your password.' => '请重置您的密码。',
	'Failed to reset password! Please try again.' => '重置密码失败！请重新试一试。',
	'Your email has been successfully verified.' => '您的邮箱被成功验证。',
	'Your email has not been verified! Please try again.' => '您的邮箱验证失败！请重新试一试。',
	
	///\vendor\yongtiger\yii2-user\src\models\Verify.php
	'User ID' => '用户ID',
	'Password Verified At' => '密码验证时间',
	'Email Verified At' => '邮箱验证时间',

	///\vendor\yongtiger\yii2-user\src\models\VerifySearch.php
	'Password Verified Date Range' => '创建日期范围',
	'Email Verified Date Range' => '更新日期范围',

	///\vendor\yongtiger\yii2-user\src\models\Profile.php
	'User ID' => '用户ID',
	'Fullname' => '姓名',
	'Firstname' => '姓氏',
	'Lastname' => '名字',
	'Gender' => '性别',
	'Language' => '语言',
	'Avatar' => '头像',
	'Link' => '网站',
	'Birthyear' => '出生年份',
	'Birthmonth' => '出生月份',
	'Birthday' => '出生日期',
	'Country' => '国家',
	'Region' => '所在地',
	'Province' => '省份',
	'City' => '城市',
	'District' => '区县',
	'Address' => '地址',
	'Telephone' => '电话',
	'Mobile' => '手机',
	'Graduate' => '毕业学校',
	'Education' => '教育程度',
	'Company' => '公司',
	'Position' => '职位',
	'Revenue' => '年薪',

	///\vendor\yongtiger\yii2-user\src\models\ProfileSearch.php
	'Created Date Range' => '创建日期范围',
	'Updated Date Range' => '更新日期范围',

	///\vendor\yongtiger\yii2-user\src\models\Count.php
	'Login Count' => '登陆次数',
	'Banned Count' => '被屏蔽次数',

	///\vendor\yongtiger\yii2-user\src\models\Status.php
	'Registration IP' => '注册IP',
	'Last Login IP' => '最后登陆IP',
	'Last Login At' => '最后登陆时间',
	'Banned At' => '被屏蔽时间',
	'Banned Reason' => '被屏蔽原因',

	///\vendor\yongtiger\yii2-user\src\models\StatusSearch.php
	'Last Login Date Range' => '最后登陆日期范围',
	'Banned Date Range' => '被屏蔽日期范围',

	///\vendor\yongtiger\yii2-user\src\models\Preference.php
	'Locale' => '语言环境',
	'Time Zone' => '时区',
	'Datetime Format' => '日期时间格式',
	'Date Format' => '日期格式',
	'Time Format' => '时间格式',
	'(Select locale ...)' => '(请选择语言环境)',
	'(Select time zone ...)' => '(请选择时区)',
	'(Select datetime format ...)' => '(请选择日期时间格式)',
	'(Select date format ...)' => '(请选择日期格式)',
	'(Select time format ...)' => '(请选择时间格式)',


	/**
	 * Views
	 */
	///\vendor\yongtiger\yii2-user\src\views\security\signup.php
	'Signup' => '注册',
	'Please fill out the following fields:' => '请填写下列内容：',

	///\vendor\yongtiger\yii2-user\src\views\security\login.php
	'Login' => '登陆',
	'If you forgot your password you can [{reset it}].' => "如果您忘记密码，您可以 [{reset it}]。",
	'reset it' => '重置',

	///\vendor\yongtiger\yii2-user\src\mail\recover-password-html.php
	///\vendor\yongtiger\yii2-user\src\mail\recover-password-text.php
	'Hello ' => '您好 ',
	'Follow the link below to reset your password:' => '请点击下面的链接重置密码：',

	///\vendor\yongtiger\yii2-user\src\mail\activate-status-html.php
	///\vendor\yongtiger\yii2-user\src\mail\activate-status-text.php
	'Follow the link below to activate your account:' => '请点击下面的链接激活账户：',

	///\vendor\yongtiger\yii2-user\src\mail\verify-email-html.php
	///\vendor\yongtiger\yii2-user\src\mail\verify-email-text.php
	'Follow the link below to verify your email:' => '请点击下面的链接验证邮箱：',

	///\vendor\yongtiger\yii2-user\src\views\account\index.php
	//////[Yii2 uesr:account]
	'Account Security' => '账户安全',
	'Manage your personal account security information.' => '管理您的个人账安全户信息。',
	'Username is not set' => '用户名没有设置',
	'Set' => '设置',
	'Change' => '更改',
	'Email is not set' => '邮箱没有设置',
	'Last verified at:' => '最后验证时间：',
	'Verify email' => '验证邮箱',
	'Last updated at:' => '最后更新时间：',
	'Danger!' => '危险！',
	'Password is not set' => '密码没有设置',
	'Oauth' => '第三方登陆',
	'Setup' => '设置',
	'Connect' => '绑定',
	'Disconnect' => '解绑',

	///\vendor\yongtiger\yii2-user\src\views\account\change.php
	'Save' => '保存',
	//////[Yii2 uesr:account]
	'You must provide your account password when changing' => '更改时必须提供您的账户密码',

	///\vendor\yongtiger\yii2-user\src\mail\account-verification-email-html.php
	///\vendor\yongtiger\yii2-user\src\mail\account-verification-email-text.php
	//////[Yii2 uesr:account]
	'Follow the link below to verify your email:' => '请点击下面的链接验证您的邮箱：',

	///\vendor\yongtiger\yii2-user\src\views\token\sendToken.php
	'Send activation email' => '发送账户激活邮件',
	'Please fill out your registration email. A link to activation will be sent there.' => '请填写您注册时的邮箱，系统将发送激活账户的邮件。',
	'Request password reset' => '请求密码重置',
	'Please fill out your registration email. A link to reset password will be sent there.' => '请填写您注册时的邮箱，系统将发送重置密码的邮件。',
	'Please fill out your registration email. A link to verify email will be sent there.' => '请填写您注册时的邮箱，系统将发送邮箱验证的邮件。',
	'Send' => '发送',

	///\vendor\yongtiger\yii2-user\src\views\user\index.php
	'Create' => '创建',
	'Update' => '更新',
	'Batch Delete' => '批量删除',
	'Are you sure you want to delete? This is a non-recoverable operation!' => '您确定要删除吗？此操作不可恢复！',
	'User List' => '用户列表',
	'profile' => '用户资料',
	'Profile' => '用户资料',
	'verify' => '用户验证',
	'Verify' => '用户验证',
	'status' => '用户状态',
	'Status' => '用户状态',
	'count' => '用户统计',
	'Count' => '用户统计',

	///\vendor\yongtiger\yii2-user\src\views\user\_search.php
	'Search' => '搜索',
	'Reset' => '重置',

	///\vendor\yongtiger\yii2-user\src\views\user\create.php
	'Create User' => '创建用户',
	'User List' => '用户列表',

	///\vendor\yongtiger\yii2-user\src\views\user\update.php
	'Update User' => '更新用户',

	///\vendor\yongtiger\yii2-user\src\views\user\_form.php
	'(Please select ...)' => '(请选择 ...)',
	'role_admin' => '站长',
	'role_super_moderator' => '超级版主',
	'role_moderator' => '版主',
	'role_user' => '普通用户',
	'inactive'  => '未激活',
	'active' => '已激活',
	'Male' => '男',
	'Female' => '女',

	///\vendor\yongtiger\yii2-user\src\views\user\view.php
	'View User' => '查看用户',
	'Are you sure you want to delete this item?' => '您确定要删除此项吗？',
	'Delete' => '删除',

	///\vendor\yongtiger\yii2-user\src\views\profile\index.php
	'User Profile List' => '用户个人资料列表',

	///\vendor\yongtiger\yii2-user\src\views\profile\update.php
	'Update User Profile' => '更新用户个人资料',

	///\vendor\yongtiger\yii2-user\src\views\profile\view.php
	'View User Profile' => '查看用户个人资料',

	///\vendor\yongtiger\yii2-user\src\views\profile\_form.php
	'Primary School' => '小学',
	'Junior High School' => '初中',
	'High School' => '高中',
	'Secondary School' => '职高',
	'Bachelor' => '本科',
	'Master' => '硕士',
	'Doctor' => '博士',
	'P.H.D.' => '博士后',
	'Staff' => '普通职员',
	'Engineer' => '工程师',
	'Secretary' => '秘书',
	'Manager' => '经理',
	'CEO' => 'CEO',
	'0-10k' => '0-10万',
	'10k-20k' => '10-20万',
	'20k-50k' => '20-50万',
	'50k-100k' => '50-100万',
	'100k+' => '100万以上',

	///\vendor\yongtiger\yii2-user\src\views\verify\index.php
	'User Verify List' => '用户验证列表',

	///\vendor\yongtiger\yii2-user\src\views\verify\update.php
	'Update User Verify' => '更新用户验证',

	///\vendor\yongtiger\yii2-user\src\views\verify\view.php
	'View User Verify' => '查看用户验证',

	///\vendor\yongtiger\yii2-user\src\views\count\index.php
	'User Count List' => '用户统计列表',

	///\vendor\yongtiger\yii2-user\src\views\count\update.php
	'Update User Count' => '更新用户统计',

	///\vendor\yongtiger\yii2-user\src\views\count\view.php
	'View User Count' => '查看用户统计',

	///\vendor\yongtiger\yii2-user\src\views\status\index.php
	'User Status List' => '用户状态列表',

	///\vendor\yongtiger\yii2-user\src\views\status\update.php
	'Update User Status' => '更新用户状态',

	///\vendor\yongtiger\yii2-user\src\views\status\view.php
	'View User Status' => '查看用户状态',

	///\vendor\yongtiger\yii2-user\src\views\preference\index.php
	'User Preference List'  => '用户偏好设置列表',

	///\vendor\yongtiger\yii2-user\src\views\preference\update.php
	'Update User Preference'  => '更新用户偏好设置',

	///\vendor\yongtiger\yii2-user\src\views\preference\view.php
	'View User Preference' => '查看用户偏好设置',
];
