<?php ///[i18n:Long Text Translation]
///such as: 'Sorry, we are unable to reset password ...' => 'Sorry, we are unable to reset password for the provided email address.',

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [

	///\vendor\yongtiger\yii2-user\src\models\SignupForm.php
	'The username only contains letters ...' => 'The username only contains letters, Chinese characters, Numbers, underscores, and cannot begin with Numbers and underscore.',	///[Yii2 uesr:username]

	///\vendor\yongtiger\yii2-user\src\models\ActivationForm.php
	'Your account has been successfully activated ...' => 'Your account has been successfully activated. You can now log in using the username and password you chose during the registration.',	///[Yii2 uesr:activation via email:activation]

];
